/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ThymeleafPure;

import java.io.StringWriter;

import org.thymeleaf.ITemplateEngine;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;
import org.thymeleaf.templateresolver.ClassLoaderTemplateResolver;

public class Library {
    
	public static void main(String[] args) {
		ITemplateEngine engine = createEngine();
		Context ctx = new Context();
		ctx.setVariable("name", "Pesho"); 
		
		StringWriter sw = new StringWriter();
		engine.process("test.html", ctx,sw);
		
		System.out.println(sw.toString());
		
	}
	
	
	private static TemplateEngine createEngine() {
		TemplateEngine engine = new TemplateEngine();
		engine.setTemplateResolver(new ClassLoaderTemplateResolver());
		return engine;
	}
	
	
}
